window.AHAM_PRODUCTS = [
  {
    id: "chan-001",
    title: "Pure Chanderi Silk Saree",
    subtitle: "Zari Border • Festive Edit",
    price_inr: 8499,
    tags: ["silk", "zari", "festive", "new"],
    fabric: "Chanderi Silk",
    occasion: "Festive / Wedding",
    weave: "Handwoven",
    care: "Dry Clean",
    description: "A refined Chanderi silk saree with a festive zari touch. Lightweight drape, premium finish.",
    image_count: 5
  },
  {
    id: "chan-002",
    title: "Chanderi Cotton Silk Saree",
    subtitle: "Everyday Elegance • Soft Feel",
    price_inr: 3499,
    tags: ["cotton-silk", "everyday"],
    fabric: "Chanderi Cotton Silk",
    occasion: "Everyday / Work",
    weave: "Handwoven",
    care: "Dry Clean",
    description: "Breathable cotton-silk blend with a graceful drape — ideal for daily wear.",
    image_count: 5
  },
  {
    id: "chan-003",
    title: "Chanderi Tissue Saree",
    subtitle: "Soft Shimmer • Occasion Wear",
    price_inr: 9999,
    tags: ["tissue", "occasion", "new"],
    fabric: "Chanderi Tissue",
    occasion: "Occasion / Evening",
    weave: "Handwoven",
    care: "Dry Clean",
    description: "A delicate tissue shimmer with an elegant fall — designed for standout occasions.",
    image_count: 5
  },
  {
    id: "chan-004",
    title: "Chanderi Buti Saree",
    subtitle: "Classic Motifs • Timeless",
    price_inr: 7499,
    tags: ["silk", "classic"],
    fabric: "Chanderi Silk",
    occasion: "Festive / Traditional",
    weave: "Handwoven",
    care: "Dry Clean",
    description: "Traditional buti motifs with a premium texture. Elegant, timeless, and versatile.",
    image_count: 5
  },
  {
    id: "chan-005",
    title: "Chanderi Minimal Stripe Saree",
    subtitle: "Modern • Understated",
    price_inr: 4999,
    tags: ["cotton-silk", "modern"],
    fabric: "Chanderi Cotton Silk",
    occasion: "Everyday / Semi-formal",
    weave: "Handwoven",
    care: "Dry Clean",
    description: "Clean stripes for a contemporary look while keeping the classic Chanderi charm.",
    image_count: 5
  },
  {
    id: "chan-006",
    title: "Chanderi Zari Border Saree",
    subtitle: "Wedding Ready • Rich Finish",
    price_inr: 8999,
    tags: ["zari", "wedding"],
    fabric: "Chanderi Silk",
    occasion: "Wedding / Festive",
    weave: "Handwoven",
    care: "Dry Clean",
    description: "A rich zari border for a celebratory look — premium drape and elegant presence.",
    image_count: 5
  }
];
